lib/image-transform.js
lib/transformers/cloudinary.js
lib/transformers/imgix.js
test/unit/lib/image-transform.js
test/unit/lib/transformers/cloudinary.js
test/unit/lib/transformers/imgix.js

Refactoring the `ImageTransform` class to stop using getters/setters. This should be a bit clearer/easier to understand now.

Refactor the ImageTransform class

---

docs/index.html

This resolves #2. A lot of this is copied from/based on the existing Image Service documentation.

Flesh out the service endpoint documentation

---

lib/image-service.js
test/unit/lib/image-service.js
test/unit/mock/http-proxy.mock.js

The headers that come back from Cloudinary and Imgix are a bit
inconsitent, and they include a lot of stuff we don't really want to
send as part of the response.
This removes them and sets consistent headers no matter where the image
comes from.

Add a proxy response handler to tidy up headers

---

.eslintrc.js
lib/middleware/get-cms-url.js
lib/routes/v2/images-debug.js
lib/routes/v2/images-raw.js
test/integration/v2/images-raw.js
test/unit/lib/middleware/get-cms-url.js

This mirrors the behaviour of the original image service, first
attempting to load an image from the V1 API and then trying V2.
In order to utilise the proxying behaviour of this service we
don't load the image, we make a HEAD request to verify that an
image is available.
If neither can be found then we error.

Handle the ftcms custom scheme

---

lib/routes/v2/images-svgtint.js
package.json
test/integration/v2/images-svgtint.js

This adds partial support for #12. The next part of this work is routing any SVG image requests through this additional layer if they have a tint parameter.

Implement an SVG tinting endpoint

---

lib/middleware/process-image-request.js

This doesn't have tests yet because I want to see how it works on qa – third party services don't have access to my local server and so the routing doesn't work properly. I'll be opening a second PR with automated tests once I know this works.

Route tinted SVGs through the svgtint endpoint

---

config.js
lib/image-service.js
lib/image-transform.js
lib/middleware/process-image-request.js
test/unit/lib/image-service.js
test/unit/lib/image-transform.js
test/unit/lib/middleware/process-image-request.js

SVG headers weren't being set properly, and a format of "auto" would never result in SVGs being sent. This fixes it and adds some tests to prevent it from happening again.

Fix SVG header sending and write tests

---

lib/middleware/tint-svg.js
lib/routes/v2/images-svgtint.js
test/unit/lib/middleware/handle-errors.js
test/unit/lib/middleware/process-image-request.js
test/unit/lib/middleware/tint-svg.js
test/unit/mock/n-express.mock.js
test/unit/mock/request.mock.js
test/unit/mock/svg-tint-stream.mock.js

This introduces unit tests for the SVG tinting that was added in #20. It also moves all of that code into reusable (and more testable) middleware.

Move SVG tinting into middleware and write tests

---

lib/image-transform.js
lib/middleware/handle-errors.js
lib/middleware/process-image-request.js
test/unit/lib/image-transform.js
test/unit/lib/middleware/process-image-request.js

It's more testable here and allows us to use `ImageTransform`'s colour name conversion stuff. E.g. `red` to `#ff0000`.

Move tinting validation logic into ImageTransform

---

docs/index.html
lib/image-transform.js
test/unit/lib/image-transform.js

This brings the tint parameter more in line with v1 of the service and documents how it behaves.

Default the tint parameter and document it

---

lib/image-service.js
test/unit/lib/image-service.js
test/unit/mock/http-proxy.mock.js

This attempts to address #27 by removing potential personal data from the request before proxying it to a third party. Currently we're setting the `User-Agent` header to the image service, and then removing cookies.
Are there any other common headers which might contain information that could identify the end user? I feel like I've probably missed a lot.

Anonymise user requests before proxying to a third party

---

lib/health-checks.js
lib/image-service.js
lib/routes/__gtg.js
package.json
test/unit/lib/health-checks.js
test/unit/lib/image-service.js
test/unit/mock/health-checks.mock.js

This gets us some of the way towards completing #33, adding in health-checks for Cloudinary and the S3 bucket we use to store image sets.

Add health-checks for Cloudinary and S3

---

lib/middleware/tint-svg.js
package.json
test/unit/lib/middleware/tint-svg.js

This is for backwards compatibility with v1 of the image service. Some SVGs break slightly if we tint the stroke colour too.

Disable tinting of SVG strokes for compatibility

---

lib/middleware/handle-errors.js
lib/routes/home.js
lib/routes/v1/docs.js
test/integration/home.js
test/integration/v1/docs.js
views/error.html

- **Switch to `501 Not Implemented` for `/v1` URLs:**  
I think this makes more sense than `410 Gone`, as the resource will never have existed
- **Redirect the application index page to /v2:**  
This makes more sense than redirecting to a `501` :)

Redirect v2

---

config.js
lib/image-service.js
lib/routes/__gtg.js
lib/routes/home.js
lib/routes/v1/docs.js
lib/routes/v2/docs/api.js
lib/routes/v2/docs/compare.js
lib/routes/v2/docs/migration.js
lib/routes/v2/images-debug.js
lib/routes/v2/images-raw.js
lib/routes/v2/images-svgtint.js
lib/routes/v2/index.js
test/integration/setup.js
test/unit/lib/image-service.js
test/unit/mock/n-express.mock.js

This adds the routehandlers to both the root path and to `origami/service/image` for use with next-router.

Add ability to mount router at different locations

---

lib/middleware/convert-to-cms-scheme.js
lib/routes/v2/images-debug.js
lib/routes/v2/images-raw.js
test/unit/lib/middleware/convert-to-cms-scheme.js

This PR addresses #63, and brings v2 closer to the behaviour of v1. If a user requests a CMS image by using the full URL rather than the `ftcms` scheme, then behind the scenes we will rewrite it to make sure we take advantage of the CMS v1/v2 fallback behaviour.
This will also make it easier to correct URLs that point to region-specific S3 buckets in future.

Rewrite CMS URLs

---

lib/image-transform.js
test/integration/v2/images-debug.js
test/unit/lib/image-transform.js
test/unit/lib/transformers/cloudinary.js
test/unit/lib/transformers/imgix.js

- Use the same quality numbers as v1
- Default the image format correctly based on file extension

Make transforms more consistent with v1 of the Image Service

---

lib/image-transform.js
test/unit/lib/image-transform.js

This now matches the behaviour of Image Service v1.

Ignore the bgcolor parameter for PNGs and SVGs

---

lib/image-service.js

If the user's browser does not support `webp` or `jpegxr`, we should set a the ft-image-format key with a default value to ensure that our cdn can vary with it.

Add default image-format as a catch-all

---

Makefile
README.md
data/comparison-images.json
lib/image-service.js
package.json
public/.eslintrc.js
public/main.js
scripts/fetch-comparison-data.js
test/unit/lib/image-service.js
test/unit/mock/n-express.mock.js
views/compare.html
views/layouts/main.html

Add image formats and sizes to the comparison page. The v1 URLs are static and set in the comparison JSON; the v2 URLs are fetched on page load so that we can inspect the response information.
This allows us to manually (for now) ensure that changes we make do not result in a size gain for common images.

Comparison sizes

---

data/comparison-images.json
lib/image-transform.js
test/unit/lib/image-transform.js
test/unit/lib/transformers/cloudinary.js

We now have a different quality map for when a DPR is set, this ensures
that high-DPR images aren't huge in terms of file size.
This should address #73
(yes I know there's still an imgix transformer in there, I'll remove in another PR)

Tweak the quality values when image DPR is set

---

data/comparison-images.json
lib/middleware/map-custom-scheme.js
test/unit/lib/middleware/map-custom-scheme.js

This matches the behaviour of v1, and means that FTICON SVGs are
returned as SVGs by default when no format parameter is set.
Resolves #94

Set the format when requesting images with custom schemes

---

lib/image-service.js
test/unit/lib/image-service.js

This is required for https://github.com/Financial-Times/ft.com-cdn/pull/256 to work.
```
=============================== Coverage summary ===============================
Statements   : 100% ( 356/356 )
Branches     : 100% ( 154/154 )
Functions    : 100% ( 58/58 )
Lines        : 100% ( 355/355 )
================================================================================
```

Move image vary code from cdn to application

---

lib/image-service.js
test/unit/lib/image-service.js

This reverts commit 226d0ad127228ad9b165f04c647b8d4365e4b568.
@JakeChampion, this should be merged after the CDN deploys to prod.

Remove the hack to serve pages on /origami/

---

data/comparison-images.json
lib/middleware/process-image-request.js
lib/transformers/cloudinary.js
test/unit/lib/middleware/process-image-request.js
test/unit/lib/transformers/cloudinary.js
views/migration.html

So I know we agreed to deprecate this, but Cloudinary's support is
actually pretty good. The tints are different, but I think would allow
us to safely redirect tinted v1 images once we drop support for it.

Support tinting of non-SVG images

---

package.json

On local machine it will run `node index.js`
On heroku with a small dyno it will run `node --max_semi_space_size=2 --max_old_space_size=256 --max_executable_size=192 index.js`

Handle node memory flags via heroku-node module

---

lib/image-service.js
package.json
test/unit/lib/image-service.js

We don't use these metrics, and they're triggering a bunch of Sentry
errors. n-express 17.16.0 allows us to disable them.

Disable service metrics

---

lib/routes/v1/docs.js
test/integration/v1/docs.js

I think this is nicer behaviour - it allows users to more easily switch
between versions of the service while they're testing it. It can change
to a 410 Gone status once v1 is decommissioned.

Redirect to v1 instead of showing an error

---

lib/image-service.js
test/unit/lib/image-service.js

This gives us JPEG XR support, which wasn't working before.

Pass the user-agent through to Cloudinary

---

scripts/purge.js
views/partials/navigation.html

I know this isn't ideal, but at the moment we have pages cached that are
different because we don't purge them with a trailing slash. I've made
the links across the site consistent, and am purging these URLs now.
Later it'd be worth redirecting to remove the slash, maybe.

Purge URLs with trailing slashes

---

lib/image-transform.js
lib/middleware/convert-to-cms-scheme.js
lib/middleware/get-cms-url.js
lib/middleware/map-custom-scheme.js
test/integration/v2/images-raw.js
test/unit/lib/image-transform.js
test/unit/lib/middleware/convert-to-cms-scheme.js
test/unit/lib/middleware/get-cms-url.js
test/unit/lib/middleware/map-custom-scheme.js

Currently a querystring in a custom scheme URL is ignored. We would like
to have a way to cache-bust these URLs for use in the registry.

Allow custom scheme URLs to have querystrings

---

lib/middleware/convert-to-cms-scheme.js
lib/middleware/get-cms-url.js
lib/routes/v2/images-debug.js
lib/routes/v2/images-raw.js
test/unit/lib/middleware/convert-to-cms-scheme.js
test/unit/lib/middleware/get-cms-url.js

We were using the EU region S3 bucket to serve images with an `ftcms` scheme. We're now using the multi-region host: prod-upp-image-read.ft.com
Currently we first check v1 of the API for images, then fall back to v2. As v2 is now multi-region and where newer images will be stored, we now default to v2 and use v1 as a fallback.

FTCMS multi region

---

lib/image-transform.js
lib/middleware/process-image-request.js
test/unit/lib/image-transform.js
test/unit/lib/middleware/process-image-request.js

Currently we add `?` to the end of the uri without checking if a querystring alerady exists. This causes the tinting parameter to not work. E.G. https://www.ft.com/__origami/service/image/v2/images/raw/ftlogo:brand-myft?source=next&tint=%23FDF8F2,%23FDF8F2&format=svg should be off-white but comes back black.
This PR resolves this issue by detecting if a querystring is present already.
This issue came about due to the cachebusting feature which was added today.
I've marked this as high priority as I believe this is an issue for all ft schemes which use the svg tinter.

Format querystring correct for svg-tint urls

---

views/api.html

We now specify that the source param should be a system code, and that
non-FT requests may be rate-limited.

Clarify allowed usage of the service

---

lib/middleware/get-image-meta.js
lib/routes/v2/images.js
package.json
test/integration/v2/images-metadata.js
test/unit/lib/middleware/get-image-meta.js
test/unit/mock/n-express.mock.js
views/api.html
views/migration.html

This matches the `images/metadata` endpoint from v1, minus the cache
object. This allows users to check image dimensions before requesting
the actual image data.

Add the images/metadata endpoint

---

lib/image-transform.js
test/unit/lib/image-transform.js

This reduces the size of a lot of URLs, and the hash character would
never reach the origin image server anyway.

Strip hashes from transform URLs

---

.gitignore
Makefile
circle.yml
npm-shrinkwrap.json
package.json

WhiteSource is a tool FT have purchased which enables us to track legal and technical issues within our dependencies. We can ensure we are using dependencies with licences we agree with and that we are notified about dependencies with security vulnerabilities in a timely manner.

Add Make target for generating whitesource reports

---

lib/image-service.js
test/unit/lib/image-service.js

We don't understand their JPEG XR logic, so we're not sending them the
user-agent for now. We'll only use JPEG XR if the Accept header
indicates support.

Never send the User-Agent to Cloudinary

---

README.md
config.js
lib/image-service.js
lib/middleware/get-base-path.js
lib/middleware/process-image-request.js
lib/routes/home.js
lib/routes/v1/docs.js
lib/routes/v2/docs/api.js
lib/routes/v2/docs/compare.js
lib/routes/v2/docs/migration.js
lib/routes/v2/docs/url-builder.js
lib/routes/v2/images-svgtint.js
lib/routes/v2/images.js
lib/routes/v2/index.js
test/integration/helpers/setup-request.js
test/integration/setup.js
test/integration/v2/docs.js
test/unit/lib/image-service.js
test/unit/lib/middleware/get-base-path.js
test/unit/lib/middleware/process-image-request.js
test/unit/mock/n-express.mock.js
views/layouts/main.html
views/url-builder.html

CDNs can now send an FT-Origami-Service-Base-Path header to change the
base path across the site documentation. This ensures that when the CDN
performs rewrites, they don't break. It also allows us to access the
service from either ft.com/__origami/... or the heroku URLs without
having to mount routes twice.

Simplify routing

---

lib/image-transform.js
test/unit/lib/image-transform.js

This allows end-users to specify transform parameters without a value,
and makes V2 more compatible with V1.
Resolves #195 (cc @quarterto, @rowanbeentje)

Allow empty transform parameters

---

test/integration/setup.js

Otherwise a port in the .env file will override this, causing
integration tests to fail.

Don't specify a port for integration tests

---

lib/middleware/get-cms-url.js
lib/middleware/tint-svg.js
test/unit/lib/middleware/get-cms-url.js
test/unit/lib/middleware/tint-svg.js

This handles errors in the CMS checking middleware and the SVG tinting
middleware. Hopefully this will help us debug our intermittent
ECONNRESET errors.

Handle connection resets

---

lib/image-service.js
test/unit/lib/image-service.js
test/unit/mock/log.mock.js
test/unit/mock/origami-service.mock.js

This PR correctly handles non-200 Cloudinary responses which are so broken that they don't send their usual `X-Cld-Error` header. We saw this happen recently with the AWS failures.

Handle broken Cloudinary responses

---

lib/image-transform.js
lib/middleware/convert-to-cms-scheme.js
lib/routes/v2/images.js
test/integration/v2/images-raw.js
test/unit/lib/image-transform.js

We've seen a few HTTP/HTTPS-schemed images that are malformed,
containing only one slash after the colon. After some testing, we
discovered that V1 of the service supports both http:/foo and http:foo
URLs. V2 now does too.

Correct malformed HTTP/HTTPS schemes

---

lib/image-service.js
test/integration/v2/images-raw.js
test/unit/lib/image-service.js

During the Cloudinary issues yesterday we wanted to purge the broken images from the CDN but found that surrogate keys which contains spaces, slashes, or non-ascii characters are difficult to use. We control our surrogate keys so I thought we can strip back the keys to only alphanumeric and dashes, that way they are still human readable and simple to use when purging.

Use only alphanumeric and dashes for surrogate keys

---

lib/health-checks.js
test/unit/lib/health-checks.js
test/unit/mock/cloudinary.mock.js

This means that we're guaranteed to notice cloudinary issues within 5
minutes, and Cloudinary issues will definitely trigger healthcheck
warnings.

Cache-bust the Cloudinary health-check every 5 minutes

---

lib/image-service.js
lib/middleware/get-cms-url.js
lib/middleware/map-custom-scheme.js
lib/routes/v2/images.js
test/integration/v2/images-raw.js
test/unit/lib/image-service.js

If this lands, it would be possible to add another purge endpoint which is used to purge a specific image.
Example:
Image wanting to be purged --
https://www.ft.com/__origami/service/image/v2/images/raw/ftsocial-v2:twitter?source=docs
How to purge the image (You would need the api header set with the correct api key) --
https://www.ft.com/__origami/service/image/v2/images/purge/ftsocial-v2:twitter?source=docs
That purge endpoint could grab the surrogate key which is specific to that original image and purge it.

Unique surrogate key for each image being transformed ✨

---

lib/image-service.js
test/unit/lib/image-service.js

FTCMS image IDs are unique, any changes made to an FTCMS image will cause a new FTCMS ID to be generated. This enables us to cache these images for a huge amount of time! 🎉

Cache ftcms images in Fastly for a year

---

lib/image-service.js
test/unit/lib/image-service.js

Heroku's timeout is 30 seconds, this means we won't see those and we can
handle these errors ourselves

Set a 25 second timeout on proxy requests

---

index.js
npm-shrinkwrap.json
package.json

This may give us some performance improvements, as well as reducing the
likelihood of seeing DNS resolution errors

Cache DNS for 1 minute

---

lib/routes/v2/images.js

This will do a purge using the purge url method. The purge url method will cause the original image and all transformations of it to be purged Cloudinary and scheduled to be purged from Fastly after the purge has propagated through Cloudinary's CDN.

Add /v2/images/purge endpoint

---

lib/middleware/map-custom-scheme.js
npm-shrinkwrap.json
package.json
test/unit/lib/middleware/map-custom-scheme.js

This is no longer needed as we can purge individual images from both
Cloudinary and Fastly now.
Resolves #248.

Remove the week from custom scheme cache-busts

---

package.json

This is temporary, I'm trying to debug the memory leak we're seeing and
this is the simplest way to verify that Node.js 6.10.1 is the cause.

Try setting a specific Node.js version

---

package.json

This is temporary, verifying that 6.10.1 introduces a memory leak.

Try using Node.js 6.10.1

---

lib/cloudinary-metrics.js
lib/image-service.js
test/unit/lib/cloudinary-metrics.js
test/unit/lib/image-service.js
test/unit/mock/cloudinary.mock.js
test/unit/mock/origami-service.mock.js

This reverts commit fe3e4a01b35b6091b1446237381a9d6015aa5708.
(So it's exactly the same PR as #261)

Revert the removal of Cloudinary usage metrics

---

package.json

This should address any memory leaks that appeared in v6.10.1. I'm
un-pinning the version and using a caret again.
This resolves #264

Try Node.js 6.10.2

---

lib/health-checks.js
test/unit/lib/health-checks.js

This is waiting on a non-cached endpoint that we should be able to poll against.

Add a healthcheck for UPP images

---

lib/image-service.js
lib/routes/purge.js
lib/routes/v2/images.js
test/unit/lib/image-service.js
views/api.html
views/purge.html

- Revert the surrogate keys back to their original form. Updating a surrogate key value is a complicated task to complete for so many requests. If we updated the surrogate keys and then decided to purge one of the new surrogate keys (E.G. All webp images), it would only purge the requests that were sent with the new surrogate key and not the old one (E.G. Not all webp images would be purged).
- Updated the purging documentation to remove the incorrect surrogate-key examples and instead to inform the reader which surrogate key corresponds to the specific task they are trying to achieve.
- Made the `/v2/purge/` route use the origami-base-path value to enable this route to work correctly on FT.com
- Added the purging documentation paths to the in-built purging mechanism which is used when …

Enable purging to work from ft.com and improve the documentation

---

lib/image-service.js
test/unit/lib/image-service.js

The syntax for a User-Agent header is `<product>/<product-version> <comment>`.
Looking into the Cloudinary reports I can see that Cloudinary is currently seeing two user-agents: `Origami` and `Image`. Updating the User-Agent header to conform to the conventional syntax [1] _should_ make Cloudinary recognise our service as one user-agent instead of two.
[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#Syntax

Update user-agent to conform to specified conventional syntax

---

lib/image-service.js

http://expressjs.com/en/api.html#etag.options.table
This setting is only applied to requests which are not proxied.
For proxied requests, we use the proxied responses etag value.

Use strong etags for all non-proxied responses

---

lib/image-transform.js
lib/middleware/process-image-request.js
lib/routes/v2/images.js
lib/transformers/cloudinary.js
test/integration/v2/images-debug.js
test/unit/lib/image-transform.js
test/unit/lib/middleware/process-image-request.js
test/unit/lib/transformers/cloudinary.js

I looked at adding the immutable cache control setting into image service for cloudinary requests for FT CMS images (These are the only images we know 100% are immutable). -- http://cloudinary.com/product_updates/immutable_cache_control_response

Add immutable cache cloudinary flag for FTCMS images

---

circle.yml
npm-shrinkwrap.json
package.json
test/integration/setup.js

Node 8 does not accept null to assign a random port. Node 6/7/8 all accept 0 to assign a random port.
>Omit the port argument, or use a port value of 0, to have the operating system assign a random port, which can be retrieved by using server.address().port after the 'listening' event has been emitted. [source](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_server_listen_port_hostname_backlog_callback)

Enable Node 8 on Heroku and CI

---

circle.yml
npm-shrinkwrap.json
package.json
test/integration/setup.js

Reverts Financial-Times/origami-image-service#290
Turns out that our release script doesn't like Node.js 8 and the latest npm for some reason. I'm gonna revert this and investigate further, as we need to get some other PRs released.

Revert "Enable Node 8 on Heroku and CI"

---

lib/middleware/purge-url.js
lib/purge-from-fastly.js
test/integration/setup.js
test/unit/lib/middleware/purge-url.js
test/unit/lib/purge-from-fastly.js
test/unit/mock/base-64.mock.js
test/unit/mock/image-transform.mock.js
test/unit/mock/utf8.mock.js
views/purge.html

This issues a purge of the original image from cloudinary (which we mark to invalidate all cloudinary transforms) and then purges from Fastly using the scheme-url surrogate-key value for the particular image being purged.

Enable all transformations of an image to be purged from fastly and cloudinary

---

lib/image-service.js
test/unit/lib/image-service.js

Cache-Control: max-age is already set.
Closes https://github.com/Financial-Times/origami-image-service/issues/144.

Remove superfluous expires header

---

test/integration/v2/images-raw.test.js

Used the existing defined `.jpg` from S3 for lack of knowledge of alternatives.
Closes https://github.com/Financial-Times/origami-image-service/issues/173.

Add tests for jpeg output format when 'format' parameter is auto

---

package-lock.json
package.json

Previous versions would use the encoded form of the url, which is not what the rest of cloudinary's system does.

update to the latest version of cloudinary which uses correct signatures

---

lib/image-transform.js
test/unit/lib/image-transform.test.js

One of our more common set of client error requests are when the client has added `px` to the width and/or height parameters. 
E.G. `/v2/images/raw/ftsocial-v2:twitter?source=o-share&format=png&tint=%23FFFFFF,%23FFFFFF&width=26px`
This pull-request will turn this into a valid request by stripping the `px` before converting to a number.

Enable the width and height parameters to accept numeric strings ending in px

---

views/purge.html

We do not want to give users the ability to purge images themselves as it can be abused. Ideally they have an image publishing workflow that doesn't involve purging images. If an image needs to be purged, users can email or Slack the Origami team with a request to purge.

Remove sentence about requesting an purging API key

---

lib/middleware/handle-svg.js

We currently use xlink:href in flags to repeat the same path multiple
times. This now gets stripped, and it'd be a lot of work to update each
flag image. I've whitelisted all of the images in our image sets, which
means we should be vigilant when accepting new SVGs into our sets.

Whitelist the Origami image sets

---

lib/middleware/handle-svg.js

Some SVGs in the FT.com assets use features that are stripped by our DOM
purification. As this is a trusted source, I'm whitelisting alongside
our own image-sets.

Whitelist SVGs from ft.com/__assets

---

.circleci/config.yml
lib/image-transform.js
lib/routes/v2/docs/url-builder.js
lib/transformers/cloudinary.js
test/unit/lib/image-transform.test.js
test/unit/lib/transformers/cloudinary.test.js
views/api.html
views/url-builder.html

This allows a user to opt into their image being stretched, which FT
labs needs for a project they're working on.
I opted for `fill` instead of `stretch` because the documentation
explicitly references the [CSS3 object-fit property](https://www.w3.org/TR/css3-images/#the-object-fit). In order to keep
following the same naming conventions, we need to go with `fill`.
Closes #340 - see issue for more information.
Note: this also fixes a broken link in the form action, which
hasn't made it to production yet.

Add a "fill" option to the "fit" property

---

package.json

Our general policy is to only use LTS releases in production, I know we've discussed in-person but should we maybe write it down somewhere? I'm reminded because of this tweet:
> Quick PSA...
> Please only use LTS releases of @nodejs in production.
> Once we end of life a release, stop using it!
> – https://twitter.com/MylesBorins/status/1110960442292256772

Use Node.js 10

---

fastly/vcl/image-service.vcl
test/fastly/origami-image-service.test.js

don't include the host header or the source query parameter in the cache key to increase the cache hit ratio (host can be 3 different values, source can be any value :| )
header and source values are not used in the generation of an image and so can be removed from the cache key. 
We store in the cache key whether a source parameter did exist because we serve an error page if the source parameter is missing.
This should make FTCMS images have a much better cache hit ratio because they are requested with source parameters of `next`, `app`, `fruitcake` etc.

Increase cache hit ratio by removing parts of cache key which are not needed

---

.circleci/config.yml

> the environment the release log applies to. One of "Production",
>"Test", "Development", "Disaster Recovery". Default: "Test"
https://github.com/Financial-Times/release-log
Hopefully fixes the failing build in master: https://circleci.com/gh/Financial-Times/origami-image-service/1333?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Change staging release-log enviroment from "QA" to "Test"

---

README.md

This seems to have been left behind when we moved from whitesource to snyk

Remove whitesource api key reference in readme as we no longer use whitesource and instead use snyk

---

README.md
index.js
lib/health-checks.js
lib/middleware/convert-to-cms-scheme.js
lib/middleware/get-cms-url.js
lib/routes/v2/images.js
package-lock.json
package.json
test/integration/setup.test.js
test/integration/v2/images-debug.test.js
test/integration/v2/images-raw.test.js
test/unit/lib/middleware/convert-to-cms-scheme.test.js
test/unit/lib/middleware/get-cms-url.test.js

This ensures we still work for old Content API v1 images and work for the images coming from the new CMS called Spark

Use Content API to locate the url of an image if it exists in the Content API otherwise fallback to original logic

---

fastly/vcl/image-service.vcl

We set stale-while-revalidate cache-control directives on our responses from origin and those responses get forwarded from our shield POPs to the other POPs. When we issue a soft-purge in Fastly, Fastly marks the content as stale and serves the content in respect of the stale-while-revalidate directive. For requests which go direct from a browser to a shield POP, they get a stale response and eventually will get the newly updated response when the stale-while-revalidate time has expired. For requests which go to another POP, the request gets served a stale response and then the POP requests the same content from our shield POP, which may end up serving the stale content as well (including the cache-control directives), which the original POP will then cache for a very long time. 
The …

Avoid passing stale content from Shield POP to Edge POP

---

RUNBOOK.md

This was pointing to the Bower Registry Heroku pipeline.

Correct the pipeline URL

---

public/main.css
views/url-builder.html

Some of these elements had a label inside the label, those second labels were meant to be converted to spans.

Make extra label element a span

---

lib/transformers/cloudinary.js
test/integration/v2/images-debug.test.js
test/integration/v2/images-raw.test.js
test/unit/lib/transformers/cloudinary.test.js

>25% of your bandwidth is being used to deliver PNG images. You can save considerable bandwidth by delivering non-transparent PNGs as JPGs. If you aren’t already doing so, consider using the ‘lossy’ flag to do this conversion automatically.

convert png to jpeg if it has no alpha channel (no transparency)

---

lib/middleware/convert-to-cms-scheme.js
lib/middleware/get-cms-url.js
test/unit/lib/middleware/convert-to-cms-scheme.test.js
test/unit/lib/middleware/get-cms-url.test.js

When working with unpublished content, the content API will not respond with the image but the original image url does in fact exist and work.
This change will make the image service attempt to use the original image url if it responds with a successful HTTP status code.
This change will make origami image service work for unpublished content being authored within Spark CMS.

If Content API does not have the image, try to use the original image url and see if it exists

---

.github/workflows/deploy-to-staging.yml
.github/workflows/npm-audit-fix.yml

This will help with any future wok on renaming the default branch name.

Use the new $default-branch macro instead of hardcoding the branch name

---

.eslintrc.js
.github/dependabot.yml
.github/workflows/test.yml
.gitignore
lib/image-transform.js
lib/middleware/get-cms-url.js
lib/middleware/process-image-request.js
lib/routes/v2/images.js
lib/transformers/cloudinary.js
package-lock.json
package.json
test/integration/setup.test.js
test/integration/v2/images-debug.test.js
test/unit/lib/middleware/get-cms-url.test.js
test/unit/lib/middleware/process-image-request.test.js
test/unit/lib/transformers/cloudinary.test.js

This changes the Origami Image Service's use of Cloudinary's fetch API with their upload API and changes how the images are stored.
Previously we used the image's url as the public ID when storing on Cloudinary. This is now causing issues because the publishing platforms which use the Origami Image Service have begun to use new image urls for the same image, meaning we have thousands upon thousands of duplicate images being stored in Cloudinary. _In a short manual scan over a few minutes I found over four thousand duplicate images._
This commit makes the Origami Image Service download the image first and calculate the SHA256 of the image, using the SHA value as the public ID. This solves the issue of duplicate images because the exact same image served at different URLs will now resolve …

store images in Cloudinary using content hash as their ID

---

package-lock.json
package.json
test/unit/lib/middleware/handle-svg.test.js

This is anticipation of rewriting the handle-svg middleware completely and not wanting to modify the tests at the same time.

Rewrite the test for handle-svg to rely less on internal implementation details of the middleware

---

lib/middleware/handle-svg.js

Requires https://github.com/Financial-Times/origami-image-service/pull/623 first
This refactor fixes a bug which occurs when the requested SVG is a 404 and the handle-svg module throws an `Error: Parse Error: User callback error`
https://sentry.io/organizations/financial-times/issues/986368588/?project=97641&query=is%3Aunresolved&sort=freq&statsPeriod=14d

Refactor handle-svg to use axios instead of request 

---

lib/image-service.js
lib/middleware/get-cms-url.js
lib/middleware/handle-svg.js
lib/middleware/process-image-request.js
lib/routes/v2/images.js

This will make our Sentry alerts less noisy as we should only be receiving Sentry alerts for issues within the application rather than alerts for when a client provided image url is a 404/500/not-an-image.

stop adding client errors to Sentry as these are not solvable by the application

---

lib/middleware/get-cms-url.js
lib/middleware/handle-svg.js
lib/middleware/process-image-request.js
test/unit/lib/middleware/get-cms-url.test.js
test/unit/lib/middleware/handle-svg.test.js

These errors are all triggered by creating an invalid Image Service URL which means that they would always be a client error and are safe to cache indefinitely.
To fix these errors the client would need to update their URL, which means it is a different object in our CDN cache.

Increase caching time of client misconfiguration errors

---

lib/middleware/process-image-request.js

We made a call to the Cloudinary Resource API to check if the image was already uploaded. It turns out that API call is not required as the Upload API call does not upload the image if it already exists in Cloudinary.
Using the Upload API with `overwrite` set to `false` will upload the image to cloudinary if it does not already exist. If it does already exist it returns an object which has the metadata for the already uploaded image.
This has a side-benefit of not using an API call which is rate-limited to 5000 calls per hour, which we regularly were hitting

Make the cloudinary upload process faster by avoiding the resource api call

---

lib/middleware/process-image-request.js

we have 30 seconds to deal with a request in heroku, let's use at most 20 of those seconds downloading the original image. Hopefully this will reduce the amount of time-out errors we are throwing.

increase the timeout for downloading the original image to 20 seconds

---

lib/middleware/handle-svg.js
lib/middleware/process-image-request.js
test/unit/lib/middleware/handle-svg.test.js

When the original image returns a 4xx or higher, let's cache the response for 5 minutes to avoid being overloaded by loads of requests for that image.

reduce load on origin servers by increasing the cache for bad responses

---

lib/middleware/process-image-request.js
test/unit/lib/middleware/process-image-request.test.js

if the image is too large to upload, let's cache the error response for 5 minutes to help avoid load on the Heroku applications and let's not capture the error in Sentry because it is a client error.

Improve handling of images which are too large to upload to Cloudinary

---

lib/middleware/process-image-request.js
test/unit/lib/middleware/process-image-request.test.js

Recently a few files have been uploaded into the universal-publishing (UPP) image buckets which are invalid images and Cloudinary correctly throws an error when we try to upload and optimise them.
Let's cache these errors in Fastly to avoid lots of requests hitting the origin and mark the errors to not be entered into sentry because they are not something we can resolve.
We still have splunk logs for the errors so we can see if we get an increase in these types of errors though 👍

do not record error in sentry if the original file is an invalid image file because this is a client error and not an app error

---

lib/middleware/process-image-request.js
test/unit/lib/middleware/process-image-request.test.js

Handling errors for:
- dns timeouts - cached for 30 seconds because this is recoverable based on traffic load to origin.
- unreachable networks - cached for 30 seconds because the network should come back online.
- invalid certificates which causes the request to fail - cached for a shortish duration because the certificate could get updated and the request would then work again.
- invalid characters in a url -- these can be cached for a very long time because it will always return an error.

Cache more errors in fastly and do not record them in sentry

---

lib/routes/v2/images.js
test/integration/v2/images-raw.test.js

We had previously only fixed this type of mistake for http url which resolved to an asset stored in UPP and not for all http urls.

Fix image requests where only one slash was supplied after `http:`

---

.github/workflows/automerge.yml
Makefile
lib/routes/v2/images.js
package-lock.json
package.json
test/integration/v2/images-raw.test.js
test/unit/lib/middleware/process-image-request.test.js

The old blogs domain is still being used for images and the domain no longer exists. We should replace the old domain with the new domain to make these images still work.
Currently we get roughly 4 thousand image requests for the old domain each day.

Redirect old blogs domain images to the new blogs domain

---

lib/image-service.js
lib/middleware/get-cms-url.js
lib/middleware/handle-svg.js
lib/middleware/process-image-request.js
test/unit/lib/image-service.test.js
test/unit/lib/middleware/get-cms-url.test.js
test/unit/lib/middleware/handle-svg.test.js
test/unit/lib/middleware/process-image-request.test.js

- Misformatted hostnames can be cached for a long time because it is a client issue in the hostname and the hostname is part of the cache-key we use in Fastly, the only waay the client can fix the issue is to change their hostname, which would mean a new cache-key is used.
- Domains which have no name-server configured can be fixed by the client without changing anything which modifies our cache-key, so we need to use a short cache time.
- I've removed the check for ENOTFOUND errors to have been thrown by a system call because we no longer use the system dns implementation. Our new implementation does not add a `syscall : 'getaddrinfo'` property to the errors.

 Add error handling for misformatted hostnames and no name-servers for a domain

---

lib/middleware/process-image-request.js
test/unit/lib/middleware/process-image-request.test.js

Fixes https://sentry.io/organizations/financial-times/issues/1907330565/?project=97641

only check content-type if it exists and is a string.

---

lib/create-error-from-axios-error.js
lib/middleware/get-cms-url.js
lib/middleware/handle-svg.js
lib/middleware/process-image-request.js
test/unit/lib/middleware/get-cms-url.test.js
test/unit/lib/middleware/handle-svg.test.js
test/unit/lib/middleware/process-image-request.test.js

These errors are thrown and handled in at least three different parts of the codebase:
- The part which handles tinting SVGs.
- The part which converts ftcms images to their http url
- The part which download the image and then uploads it to cloudinary.
They all handle these errors in the same way, instead of copying and pasting the error handing code between them, let's put it in a module to reuse it.

Extract the axios error handling into it's own module for reuse

---

README.md
views/url-builder.html

Fixes https://github.com/Financial-Times/origami-image-service/issues/653

Add explanation for non transparent pngs converted to jpg

---

README.md
lib/middleware/process-image-request.js

At some point in the history of this project we made all SVGs go through svg endpoint to start sanitizing SVGs in order to protect against a cross-site-scripting attack but we forgot to update the troubleshooting section to mention that all SVGs would not work when running locally without supplying a valid `HOSTNAME` environment variable.
This pull-request updates the troubleshooting section and a code comment to mention that it applies to all SVGs now.

Update troubleshooting section for SVGs to mention it applies to all SVG requests

---

README.md
about.json
lib/health-checks.js
lib/middleware/get-cms-url.js
lib/routes/v2/docs/url-builder.js
lib/transformers/cloudinary.js
test/integration/v2/images-debug.test.js
test/integration/v2/images-metadata.test.js
test/unit/lib/middleware/convert-to-cms-scheme.test.js
test/unit/lib/middleware/get-cms-url.test.js
test/unit/lib/middleware/purge-url.test.js
views/index.html

This will remove the mixed content warning we get on the origami-image-service homepage.
This will also use https for more of our image backends such as prod-upp-image-read.ft.com and im.ft-static.com 👍

use https on links which support it

---

.github/workflows/test.yml
package-lock.json
package.json

Origami spec 2.0 components require npm 7.
I figured it might be good to get our services onto npm 7 in preparation for the components updates

Update to node 14 LTS and npm 7

---

Makefile
test/integration/v2/images-debug.test.js
views/api.html

The only reason it was ever put in beta is because editorial didn’t trust the use of AI for image cropping and asked for it not to be used on FT.com
We are not planning to remove the gravity feature from our API, so let's remove the beta label

Remove beta label from the gravity field

---

.github/workflows/deploy-to-dev.yml
.github/workflows/deploy-to-staging.yml
README.md
test/integration/setup.test.js

We need this functionality to have tests written for the new way of serving image-sets (#763)
As the image-sets will be served from the application instead of a separate domain, the integration tests for image-sets will only work when the integration test server is on a domain which cloudinary can access (not localhost)
This setup is the same as the setup we have in the origami build service (https://github.com/Financial-Times/origami-build-service/pull/411)

Enable the integration tests to run against a live server

---

lib/routes/v2/docs/url-builder.js

Express gets `request.hostname` from the Host HTTP header, I think it's safe to use in this way

fix: url builder output in production where the hostname env is not set

---

lib/routes/v2/docs/url-builder.js

this is set to the heroku hostname by fastly

Do not use `request.hostname` for url builder output

---

image-sets/fticon/v1/deprecated.json

Underscores are not allowed in our icon naming. mute_notifications has been replaced by mute-notifications
resolves https://github.com/Financial-Times/fticons/issues/74

deprecate mute_notifications as it is replaced by mute-notifications

---

lib/middleware/get-cms-url.js
test/unit/lib/middleware/get-cms-url.test.js

Recently the content api had an issue where it was returning 404s by
accident for requests which should have returned a 200. We then cached
those invalid responses for 1 year, which was unfortunate for our users
as when the content api was fixed, we were still serving 404s.
This change will make it so that we cache content api 404s for only 5
minutes, which is long enough to stop our servers getting overloaded
and is short enough for our users to retry the requests in case the 404
was an accident

fix: cache ftcms requests which 404 only for 5m instead of 1 year

---

lib/image-service.js
lib/middleware/origami-image-service-supress-ft-com-error-page.js.js
lib/middleware/origami-image-service-timing-allow-origin.js
test/integration/v2/images-metadata.test.js
test/integration/v2/images-raw.test.js
test/integration/v2/images-svgtint.test.js
test/integration/v2/imagesets.test.js
test/integration/v2/imagesetsjson.test.js
test/unit/lib/image-service.test.js

as these are response headers, it makes sense to set them in the application.
setting these in the application make them simpler to test and change as it does not invlove touching the ft.com-cdn
if this is merged and release, we can then remove these lines from the ft.com-cdn -> https://github.com/Financial-Times/ft.com-cdn/blob/98bd0a5722f7cc4280e08a3f7dc1d3df240f966b/src/vcl/origami-image-service.vcl#L57-L58
if [this pr](https://github.com/Financial-Times/origami-image-service/pull/788) is also merged and released, then we can remove the entire `origami_image_service_fetch` subroutine from ft.com-cdn

Set timing-allow-origin and ft-supress-friendly-error response headers within the application

---

lib/middleware/process-image-request.js
test/unit/lib/middleware/process-image-request.test.js

This is to help debug the app-badge imageset. The images [404 in prod](https://origami-image-service-eu.herokuapp.com/__origami/service/image/v2/images/raw/app-badge-v1:apple?source=origami-image-service-website)
but work locally, in [dev](https://origami-image-service-dev.herokuapp.com/__origami/service/image/v2/images/raw/app-badge-v1:apple?source=origami-image-service-website), and [qa](https://origami-image-service-qa.herokuapp.com/__origami/service/image/v2/images/raw/app-badge-v1:apple?source=origami-image-service-website).
Relates to: https://github.com/Financial-Times/origami-image-service/pull/799

backstage: log 4.x.x errors when downloading an image from its source

---

lib/middleware/process-image-request.js

If we have an image in in memory cache:
https://github.com/Financial-Times/origami-image-service/blob/5254832481ef794909eca717d5f27e75147eebed/lib/middleware/process-image-request.js#L95
Then we don't check if the image is a gif to remove the avif transform:
https://github.com/Financial-Times/origami-image-service/blob/5254832481ef794909eca717d5f27e75147eebed/lib/middleware/process-image-request.js#L175
This is a bit not nice, and could use a refactor, but should
stop the production issue without removing avif support.

fix: do not apply avif to gif after initial request

---

lib/image-service.js
package-lock.json
package.json

We have seen many `ENETUNREACH` errors since Apr 6, when this was released. I'm not sure why. Let's see if removing better-lookup will help.

fix: remove better-lookup

---

lib/image-service.js
lib/transformers/cloudinary.js
test/integration/v2/images-debug.test.js
test/unit/lib/image-service.test.js
test/unit/lib/transformers/cloudinary.test.js

Origami Image Service errored intermittently, in waves. We were getting around ~10,000 errors a day. We mitigated by switching to http requests.
We've found Cloudinary are backed by 3 cdns:
resa.cloudinary.com (akamai)
resf.cloudinary.com (fastly)
resc.cloudinary.com (cloudfront)
When we proxy image requests to resc.cloudinary.com (cloudfront) we got errors. We got no errors when proxying image service requests via Cloudinary's other two cdn providers. Alex pointed out this could explain the intermittent, wave-like nature of the errors we're seeing as dns cache expires.
We were able to output the full openssl log using:
```
proxyRequest.socket.enableTrace();
```
https://github.com/Financial-Times/origami-image-service/pull/823/files#diff-ba85e65e5381efabd2a2e48851c18adee2030e7d64e82265f3a0 …

[OR-140] Fix Cloudinary SSL Handshake Error, revert back to https

---

README.md

No longer used since moving to change management api https://github.com/Financial-Times/origami-image-service/pull/417

docs: Remove env docs for RELEASE_LOG_API_KEY

---

lib/image-transform.js
lib/routes/v2/docs/url-builder.js
lib/transformers/cloudinary.js
test/unit/lib/image-transform.test.js
views/api.html
views/url-builder.html

Enables requests to the API with `fit` set to `pad`. This will allow images to be scaled whilst maintaining the original aspect ratio. Any white space that occurs after the transform will bet set with a colour from `bgcolor`.
Partially completes OR-240. FTEdit would like the background to also be transparent, but this doesn't appear to work without further changes. Releasing this as an increment will allow them to test if this feature meets their requirements whilst we work on the transparency issue.

feat: transform images with Cloudinary's 'pad' option

---

image-sets/fticon/v1/mute.svg

We will also use the mute icon to mean "no audio avaliable", with a clarifying label. We believe the updated icon can convey both meanings more affectively. It also aligns with the mute icon used on IOS, MacOS, and YouTube https://docs.google.com/document/d/1aKhbRfMnCthZ-6D5eT82lpMmBeCcywNl9HzQakBf6lU/edit#heading=h.tv4ot1paadjg

Update fticon mute

---

package-lock.json
package.json
scripts/delete-old-images-from-cloudinary.js

To reduce Cloudinary costs we want to delete old images. We have a script to do this, which is run every day via a "Heroku scheduler" on origami-image-service-eu. However this script errors due to api limits, it's stuck trying to delete the same images on loop.
- Pass `next_cursor` to Cloudinary search, so the next results are returned correctly.
- Set `keep_original` when deleting images. This will delete only derived images – transforms – not the originals. We don't promise to keep originals and expect the source images to remain available, but I don't want to have to explain that to any angry product teams right now.
- Update logs to help us monitor the script. If it deletes many images and then fails before the script exits, we want to know.
We probably don't want to run this updated …

fix: scripts/delete-old-images-from-cloudinary.js [OR-298]

---

lib/middleware/get-cms-url.js
package-lock.json
package.json
test/integration/v2/images-raw.test.js
test/unit/lib/middleware/get-cms-url.test.js

We are using [uuid](https://www.npmjs.com/package/uuid) to validate img uuids passed to the image service. It seems that all our internal APIs use the same structure for generating UUIDs and this library should be enough to validate if img UUIDs are valid or not. 
From manually testing and making a few requests to image service seems to work and we return 400 before we make malicious requests to internal APIs.

backstage: validate uuid before making requests to internal apis

---

lib/image-service.js
lib/image-transform.js
lib/transformers/cloudinary.js
test/unit/lib/transformers/cloudinary.test.js
views/api.html

Run locally and hit with: 
http://localhost:8080/__origami/service/image/v2/images/raw/https%3A%2F%2Fd1e00ek4ebabms.cloudfront.net%2Fproduction%2Fa88c2b59-ac2d-4f70-a68a-57b8499bd70f.jpg?source=next-article&fit=scale-down&quality=highest&width=700&dpr=1&overlay=https://ft-next-assets-prod.s3.eu-west-1.amazonaws.com/assets/ft-banner.png&overlay_height=0.5&overlay_y=30
You should see:

feat: overlay images.

---

views/layouts/main.html

Polyfill has not been FT owned for awhile, and has recently been sold. We are able to meet our browser support policy without it.

chore: Remove polyfill.io use

---

opentelemetry.js

This should mean each process will send metrics with a unique service instance ID.
> For applications running behind an application server (like unicorn), we do not recommend using one identifier for all processes participating in the application. Instead, it’s recommended each division (e.g. a worker thread in unicorn) to have its own instance.id.
From https://opentelemetry.io/docs/specs/semconv/resource/#service-experimental.
* https://github.com/Financial-Times/origami-image-service/pull/863

fix: let the OTel SDK set the service instance ID

---

lib/middleware/get-headshot-url.js

In our newsletter in Spark, if an author has a three or more part name, their photo breaks. 
I changed the regex to include three or more barrelled names getting accepted.

fix: three-barrelled-name

---

README.md
about.json
lib/create-error-from-axios-error.js
lib/image-service.js
lib/middleware/get-cms-url.js
lib/middleware/get-headshot-url.js
lib/middleware/handle-svg.js
lib/middleware/helpers/errorHelpers.js
lib/middleware/helpers/transformHelpers.js
lib/routes/v2/images.js
package-lock.json
package.json
scripts/delete-old-images-from-cloudinary.js
test/unit/lib/image-service.test.js
test/unit/lib/middleware/process-image-request.test.js

**What**
- Current subscription to Sentry will expire in Q4 2024. A reference to the Sentry SDK needs to be cleared.
**How**
- Remove all Sentry reference from code base
- Remove Heroku envs related to Sentry 
- Remove the project from Sentry, if possible. [access required]

[Remove] Sentry from the image service.

---

lib/middleware/get-cms-url.js
lib/middleware/helpers/regex.js
lib/middleware/helpers/validate.js
package-lock.json
package.json
test/integration/v2/images-raw.test.js
test/unit/lib/middleware/get-cms-url.test.js

**What**
- Remove `uuid` and adopt the native `crypto.randomUUID` functionality.
`How`
- Replace the validation functionality of uuid with the exact replica of it using regex.
- Use `crypto.randomUUID` to generate uuid for Test.
- Remove uuid packages.

[Remove] UUID

---

lib/middleware/handle-svg.js

To prevent anchor tags in untrusted SVG we made sanitisation more strict.
https://github.com/Financial-Times/origami-image-service/pull/974
This broke some legit SVGs by stripping filters

fix: Allow SVG filters
