lib/image-service.js, package.json, test/unit/lib/image-service.js, test/unit/mock/morgan.mock.js
=> Add request logging with Morgan

lib/image-transform.js, test/unit/lib/image-transform.js
=> Map unversioned schemes to specific image set versions

.gitignore, lib/routes/__about.js, public/__about.json
=> "__about" endpoint added

lib/middleware/handle-errors.js, test/integration/setup.js, test/unit/lib/middleware/handle-errors.js, test/unit/mock/n-express.mock.js, views/error.html
=> Render the error pages with Handlebars

data/comparison-images.json, lib/image-service.js, test/integration/helpers/it-does-not-respond-with-header.js, test/integration/helpers/it-responds-with-header.js, test/integration/v2/images-raw.js, test/unit/lib/image-service.js
=> Content dpr header new implementation

README.md, config.js, lib/image-service.js, lib/middleware/process-image-request.js, lib/routes/home.js, lib/routes/v2/docs/compare.js, test/unit/lib/image-service.js, test/unit/lib/middleware/process-image-request.js, test/unit/mock/n-express.mock.js, views/compare.html, views/index.html, views/partials/navigation.html
This allows us to run the Image Service on a sub-path rather than
immediately after the hostname.
=> Allow setting a base URL

data/comparison-images.json, lib/routes/v2/docs/compare.js, views/compare.html, views/layouts/main.html
This PR updates the compare page to make it more useful. Still to come is the ability to view image metadata, such as content-type and content-length for size comparisons.
=> Compare page

lib/image-transform.js, test/unit/lib/image-transform.js
=> Always serve PNGs when quality is lossless

views/compare.html, views/index.html, views/migration.html
Guide people around the docs a bit more.
=> Improve the docs with some signposting

views/migration.html
Adding in the v1 and v2 URLs, and making the change that you need to
make more explicit.
=> Improve the migration guide

config.js, lib/health-checks.js, lib/image-service.js, test/unit/lib/image-service.js
This fixes the issues outlined in the [healthcheck validation tool](http://healthcheck.ft.com/validate?server=www.ft.com/__origami/service/image&host=www.ft.com&protocol=https).
=> Healthcheck validation

Makefile, README.md, config.js, package.json, test/integration/setup.js, test/unit/lib/image-service.js
Reverts Financial-Times/origami-image-service#97
=> Revert "Add ability to use next-router during dev"

public/main.css, scripts/purge.js, views/index.html, views/layouts/main.html
Improve the home page examples and move a bunch of inline CSS into a CSS file
=> Improve examples

lib/routes/v2/docs/url-builder.js, public/main.css, scripts/purge.js, views/index.html, views/layouts/main.html, views/partials/navigation.html, views/url-builder.html
Add a URL builder page. This is currently a regular form with no client-side JS stuff, I think it works better as an MVP. I can demo it for you if you like, just give me a shout.
This resolves #35.
=> URL Builder

data/comparison-images.json, lib/health-checks.js, lib/middleware/get-cms-url.js, scripts/fetch-comparison-data.js, test/unit/lib/health-checks.js, test/unit/lib/middleware/get-cms-url.js
There are a few memory leaks, all relating to our use of `fetch`. I've replaced it with `request` in all of the places where it can affect memory usage.
=> Fix memory leaks

lib/image-transform.js, lib/middleware/convert-to-cms-scheme.js, lib/routes/v2/images.js, test/integration/v2/images-raw.js, test/unit/lib/image-transform.js, test/unit/lib/middleware/convert-to-cms-scheme.js
=> Support protocol-relative urls in Image Transforms

lib/image-service.js
This will hopefully help a lot with debugging the JPEG XR issues.
=> Log image format info for debugging

data/comparison-images.json, lib/image-transform.js, lib/transformers/cloudinary.js, test/unit/lib/image-transform.js, test/unit/lib/transformers/cloudinary.js, views/api.html
This adds a `gravity` parameter which can be used to find a focal point
within the image. Currently we've added "faces" and "poi" (point of
interest) as possible values.
I've labeled this as a beta feature, as we may not end up using it.
=> Add smart cropping with the gravity parameter

README.md, index.js
See also: https://github.com/Financial-Times/origami-build-service/pull/81
=> Consistency with build service

index.js, package.json
This means that we won't lose any historical data in Graphite.
=> Specify a metrics app name

lib/routes/v2/docs/url-builder.js, views/url-builder.html
This makes it much harder for people to use the url-builder source
parameter in their applications.
=> Lock down the URL builder

.gitignore, Makefile, circle.yml, package.json
This should probably be in the service boilerplate when we create one.
=> Add Whitesource functionality once again

index.js, lib/health-checks.js, test/unit/lib/health-checks.js
This should help us debug the intermittent healthcheck failures we are
seeing in Pingdom.
=> Log healthcheck errors

lib/image-transform.js, test/integration/v2/images-raw.js, test/unit/lib/image-transform.js
Addresses https://github.com/Financial-Times/origami-image-service/issues/233#issuecomment-285324073, can explain in person – will be easier.
=> Imageset extensions

lib/image-service.js, test/unit/lib/image-service.js
=> Set surrogate cache control to a year for custom schemes

package.json
Reverts Financial-Times/origami-image-service#266
=> Revert "Try using Node.js 6.10.1"

package.json
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
=> Update to latest version of node 6 as minimum version used

lib/health-checks.js, test/integration/setup.js, test/integration/v2/images-raw.js
Repo for the new custom scheme store is https://github.com/Financial-Times/origami-imageset-data
=> use new custom scheme store (https://origami-images.ft.com) which is not under www.ft.com

README.md, lib/image-service.js, lib/image-transform.js, lib/routes/v2/images.js, test/integration/v2/images-raw.js, test/unit/lib/image-service.js, test/unit/lib/image-transform.js, views/api.html
This PR should add the flags image set (https://github.com/financial-times/origami-flag-images)
=> Flag images

lib/routes/v2/docs/url-builder.js, test/integration/v2/images-svgtint.js, views/url-builder.html
=> Expose the bgcolor parameter in the URL builder

lib/image-service.js, lib/middleware/get-cms-url.js, package-lock.json, package.json
We can't do anything about these errors, and they make up a tiny
fraction of our reporting. If they spike then we'll still see this
reflected in the Grafana dashboard and more information  will be
available in Splunk.
=> Skip Sentry for certain common error types

lib/image-transform.js, test/integration/v2/images-raw.test.js, test/integration/v2/imagesets.test.js, test/unit/lib/image-transform.test.js
I accidentally made the latest social icons be returned for ftsocial-v1 instead of ftsocial-v2, this patch fixes that issue.
=> The latest social icons is on v2, not v1.

test/integration/v2/images-svgtint.test.js
=> Remove the last image in integration tests that is not hosted by FT

public/main.css, views/index.html, views/layouts/main.html, views/partials/footer.html, views/partials/header.html
I followed the migration guides !
=> Update o-layout to v3.0.0

test/unit/lib/middleware/handle-svg.test.js, test/unit/mock/dompurify.mock.js, test/unit/mock/jsdom.mock.js
=> Add tests for SVG purification

.github/workflows/test.yml, package-lock.json, package.json
- require node 12
- upgrade `svg-tint-stream`
=> Require node 12

Makefile, package-lock.json, package.json
I've been using this for a while to help debug errors which were in sentry
=> Add an development mode which has huge stacktraces across async contexts to help debug errors.

package-lock.json, package.json, scripts/delete-old-images-from-cloudinary.js
This script will be executed by the [Heroku Scheduler Addon](https://devcenter.heroku.com/articles/scheduler) once every day on the production EU Heroku application.
=> Add script which will delete images from cloudinary which are more than 30 days old

views/partials/footer.html
Fixes https://github.com/Financial-Times/origami-image-service/issues/657
=> Update year to 2020 in footer

lib/routes/v2/docs/url-builder.js
=> only delete formData.source if we set it

README.md
it would be good to also improve the error message, as @JakeChampion has said
=> mention the ECONNREFUSED error so it appears when grepping

package-lock.json, package.json
=> Bump fticons image set

Makefile, lib/middleware/process-image-request.js, package-lock.json, package.json, test/unit/lib/middleware/process-image-request.test.js
Currently if a large video is requested then it crashes the application -- this pr will make it instead return a 400 response 👍
=> Return a 400 if the resource being requested is a video

lib/routes/v2/docs/url-builder.js, views/url-builder.html
=> fix: url builder output includes double forward slash

image-sets/fticon/v1/eye-closed.svg, image-sets/fticon/v1/eye-open.svg
Contributing guidelines: https://github.com/Financial-Times/origami-image-service/blob/main/image-sets/fticon/v1/contributing.md
- [eye-open tinted](https://www.ft.com/__origami/service/image/v2/docs/url-builder?url=https%3A%2F%2Fmedia.githubusercontent.com%2Fmedia%2FFinancial-Times%2Forigami-image-service%2Faa36b2f4364c83b0b1b2343401926a0716ab2aac%2Fimage-sets%2Ffticon%2Fv1%2Feye-open.svg&source=test&width=&height=&gravity=&format=svg&quality=&tint=blue&bgcolor=)
- [eye-open png](https://www.ft.com/__origami/service/image/v2/docs/url-builder?url=https%3A%2F%2Fmedia.githubusercontent.com%2Fmedia%2FFinancial-Times%2Forigami-image-service%2Faa36b2f4364c83b0b1b2343401926a0716ab2aac%2Fimage-sets%2Ffticon%2Fv1%2Feye-open.svg&source=test&width=&height=&gravity=&format=png&quality=&tint=&bgcolor= …
=> feat: add eye icons

image-sets/specialisttitle/v1/brand-live-ft-logo-black-letters.svg, image-sets/specialisttitle/v1/brand-live-ft-logo-standard.svg
Needed for : https://financialtimes.atlassian.net/browse/HIVE-974
=> adding ft live logo with black letters

lib/transformers/cloudinary.js, test/integration/v2/images-debug.test.js, test/unit/lib/transformers/cloudinary.test.js
Due to an intermittent openssl error causing 500 responces https://response.ftops.tech/incident/2032/
=> Do not proxy cloudinary via https

README.md
- remove empty file `:`
- update docs with doppler migration guide
=> docs: update readme to take new doppler into consideration

lib/middleware/process-image-request.js, package-lock.json, package.json, test/integration/v2/images-raw.test.js
1. Update axios. Just because.
2. Set custom User-Agent when making requests to process images.
Some CDN's block the default axios User Agent.
```
http https://i.prcdn.co 'User-Agent: axios/1.6.2\r\n' --headers
HTTP/1.1 403 Forbidden
http https://i.prcdn.co/img?cid=V99C 'User-Agent: \r' --headers
HTTP/1.1 403 Forbidden
http https://i.prcdn.co/img?cid=V99C 'User-Agent: \n' --headers
HTTP/1.1 200 Success
```
=> fix: Update use of axios to make network requests.

views/purge.html
We are talking about the source url, not the image service url.
=> docs: Improve purge by Fastly clarity

.github/.dependabot.yml, package.json
- Remove snyk ref from package.json
- Add `.dependabot.yml` for dependabot rules
TODO: once merged, disconnect repo from snyk on the website
=> [CHORE] Remove snyk

lib/middleware/helpers/cloudinaryHelper.js, lib/middleware/helpers/errorHelpers.js, lib/middleware/helpers/transformHelpers.js, lib/middleware/process-image-request.js, test/unit/lib/middleware/process-image-request.test.js
- Big refactor of the processing of image requests
- 3 helper files for transform, error handling and cloudinary setup
- Re-tested, existing functionality working
- Removed ergh hardcoded check as there is now a check for video anyway
=> [REFACTOR] Process Image Request

README.md
Update the monitoring section to add a few notes as to what to find on the updated Grafana/Splunk pages
=> [Update] Monitoring README notes

.github/workflows/deploy-to-dev.yml, .github/workflows/deploy-to-staging.yml, .github/workflows/test.yml, package-lock.json, package.json
Update uses of Node from v18 to v20
=> [Update] Node v18 to v20

.github/dependabot.yml
Update the dependabot schedule to be 1 PR per day (if available)
=> [Update] dependabot schedule

package-lock.json, package.json, scripts/delete-old-images-from-cloudinary.js
**What**
- Remove `make-promises-safe` package
**How**
- Replace it with the native way of promise handling, `try-catch` and `await`
=> [Remove] make-promises-safe package.

package-lock.json, package.json
**What** 
- Remove `trace`  and `clarify`
**How**
- Replaced by `--enable-source-maps` , which is Nodejs built in option. https://nodejs.org/docs/latest-v20.x/api/cli.html#--enable-source-maps
=> [Remove] trace and clarify.

package-lock.json, package.json
**What** 
- Remove` path-exists`, `statuses`, `denodeify`,`start-server-and-test `and `supertest`
=> [Remove] More packages.
